### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by Fluffy-Fuwafuwa** [TrashboxBobylev/Doukutsu-Randamu-Japanese-Pack#1]
Nice to meet you.
I am a user from Japan and I am enjoying playing doukutsu-randamu.
I would like to report to Trashbox Bobylev that I found some parts of the translation that I am concerned about.
Please note that I am not including parts that I am not sure if they are wrong or not due to my lack of playing experience.

-The title image seems to be rotated one letter at a time. (This is tasteful and I like it.)
-Sue's(スー) name had become Ame(アメ). Other grammatical concerns in the message have been corrected.

-The "シード(seed)" in Textbox.png looks like a "ツード". I have attached a modified image in case you are interested, but please use it only as a reference as I may have destroyed the image when creating the alpha channel.

[japanese.zip](https://github.com/TrashboxBobylev/Doukutsu-Randamu-Japanese-Pack/files/8766452/japanese.zip)

I also report that the game crashes when the "Little Man" is equipped.

![little](https://user-images.githubusercontent.com/106189561/170138931-3cd99a2d-108a-4ff5-92de-bec8b5dfd3ca.jpg)

I'm using DeepL translation to translate it into English, so sorry if there are any weird parts.
I will report back if there are any areas of concern.
Thank you very much.

**Comment by TrashboxBobylev** [comment]
Thanks for contrubuting! I'd suggest doing that using Pull Requests system next time!
